<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- This file is not a robot in and of itself, it just contains some useful tags that could be included in any robot -->

    <xacro:arg name="use_ros2_control" default="true"/>

    <xacro:property name="hull_radius" value="1.00"/>
    <xacro:property name="hull_thickness" value="0.67"/>
    <xacro:property name="hull_mass" value="1.00"/>
    <xacro:property name="wheel_radius" value="0.33"/>
    <xacro:property name="wheel_mass" value="0.1"/>

    <xacro:property name="side_length" value="${(hull_radius - wheel_radius) * sqrt(3)}"/>
    <xacro:property name="wheel_offset_x_front" value="${sqrt(3) / 6 * side_length}"/>
    <xacro:property name="wheel_offset_y" value="${side_length / 2}"/>
    <xacro:property name="wheel_offset_x_rear" value="${-sqrt(3) / 3 * side_length}"/>
    <xacro:property name="wheel_offset_z" value="${hull_thickness/2}"/>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="gray">
        <color rgba="0.33 0.33 0.33 1"/>
    </material>

</robot>